Add violations for File, FileInputStream, FileOutputStream, FileReader and FileWriter
gaul/modernizer-maven-plugin pull request #301
Opened 2024-12-12 14:25 UTC by mkarg

Modern applications should switch from NIO API to NIO2 API to allow for improved performance.

*Disclaimer: I am part of the I/O performance optimization team at OpenJDK. My intention of the current PR is to evangelize its use, so applications will run more efficient.*

2024-12-12 15:25 UTC, mkarg commented
Tests run fine on modern JDKs, but Github Actions fail because they run on JDK 8, as Java 11 tests need JDK 11 to compile...! 🤦‍♂️

2024-12-12 15:27 UTC, mkarg commented
I have deliberately replaces some Java 11 violations that would produce a paradox situation now that Java 7 violations are in place: We should definitively *not* ask people to stick with IO classes in Java 11 when we ask them to switch over to NIO2 already in Java 7! 😳

2024-12-15 18:27 UTC, gaul requested changes
This looks like a good improvement.  Could you bump the Java version to 11 in `.github/workflows/ci.yml`?  This should retain compatibility with older JDKs since `maven.compiler.source` is set to 8 in `pom.xml`.

2024-12-15 22:03 UTC, mkarg commented
> This looks like a good improvement. Could you bump the Java version to 11 in `.github/workflows/ci.yml`? This should retain compatibility with older JDKs since `maven.compiler.source` is set to 8 in `pom.xml`.

Done. 🙂

2024-12-17 06:03 UTC, merged